port = 8095

dataset.train = /scratch/hpc-prf-crnrw/weave/evaluation/ml4srm/dev-assist/dev-assist-dataset.arff
dataset.test = /scratch/hpc-prf-crnrw/weave/evaluation/ml4srm/dev-assist/dev-assist-gxa-dataset.arff

# ------ML-Plan configuration

#duration in minutes
mlplan.timeout = 60
mlplan.timeout.node = 30
mlplan.timeout.candidate = 10
mlplan.seed = 76557
mlplan.cpu = 64

#-----Empirical evaluation
jaicore.databaseConfig = ./evaluation/ml4srm/dev-assist/db.properties
jaicore.experimentConfig = ./evaluation/ml4srm/dev-assist/experiments.cnf

#-----Paths
paths.explainer = /scratch/hpc-prf-crnrw/weave/cli/src/main/java/de/fraunhofer/iem/weave/module/explainer/shap/shap_explainer.py
paths.output = /scratch/hpc-prf-crnrw/weave/evaluation/ml4srm/dev-assist/explanations
paths.python = python

shap.global.bg.samples = 500
shap.global.exp.samples = 500

shap.local.bg.samples = 250
shap.local.exp.samples = 250