# 0 = let the OS pick a free port
port = 0
dataset.train = ${WEAVE_HOME}/evaluation/ml4srm/dev-assist/dev-assist-dataset.arff
dataset.test = ${WEAVE_HOME}/evaluation/ml4srm/dev-assist/dev-assist-gxa-dataset.arff

# ------ML-Plan configuration

#duration in minutes
mlplan.timeout = 480
mlplan.timeout.node = 30
mlplan.timeout.candidate = 5
mlplan.seed = 5570
mlplan.cpu = 64

#-----Empirical evaluation
jaicore.databaseConfig = ${WEAVE_HOME}/evaluation/ml4srm/dev-assist/config/db.properties
jaicore.experimentConfig = ${WEAVE_HOME}/evaluation/ml4srm/dev-assist/config/experiments.cnf

#-----Paths
paths.explainer = ${WEAVE_HOME}/cli/src/main/java/de/fraunhofer/iem/weave/module/explainer/shap/shap_explainer.py
paths.output = ${WEAVE_HOME}/evaluation/ml4srm/dev-assist/explanations/${MODEL_TAG:-published}
paths.python = python

shap.global.bg.samples = 500
shap.global.exp.samples = 500

shap.local.bg.samples = 250
shap.local.exp.samples = 250