
dataset = ./evaluation/ml4srm/sscm/sscm.arff

# ------ML-Plan configuration

#duration in minutes
mlplan.timeout = 5
mlplan.timeout.node = 30
mlplan.timeout.candidate = 10
mlplan.seed = 7657
mlplan.cpu = 8

#-----Empirical evaluation
jaicore.databaseConfig = ./evaluation/ml4srm/sscm/db.properties
jaicore.experimentConfig = ./evaluation/ml4srm/sscm/experiments.cnf
