
dataset = ../weave/evaluation/ml4srm/swan/dataset/train/sink.arff

# ------ML-Plan configuration

#duration in minutes
mlplan.timeout = 1
mlplan.timeout.node = 20
mlplan.timeout.candidate = 5
mlplan.seed = 0
mlplan.cpu = 16

#-----Empirical evaluation
jaicore.databaseConfig = ../weave/evaluation/ml4srm/swan/config/db.properties
jaicore.experimentConfig = ../weave/evaluation/ml4srm/swan/config/experiments.cnf
