
dataset = ../weave/evaluation/ml4srm/dev-assist/dataset/train/meka-code.arff

# ------ML-Plan configuration

#duration in minutes
mlplan.timeout = 1
mlplan.timeout.node = 1
mlplan.timeout.candidate = 1
mlplan.seed = 76557
mlplan.cpu = 1

#-----Empirical evaluation
jaicore.databaseConfig = ../weave/evaluation/ml4srm/dev-assist/config/ml-plan/db.properties
jaicore.experimentConfig = ../weave/evaluation/ml4srm/dev-assist/config/ml-plan/experiments.cnf
