
dataset = ./evaluation/ml4srm/swan/cwe79/cwe79.arff

# ------ML-Plan configuration

#duration in minutes
mlplan.timeout = 60
mlplan.timeout.node = 30
mlplan.timeout.candidate = 10
mlplan.seed = 76557
mlplan.cpu = 64

#-----Empirical evaluation
jaicore.databaseConfig = ./evaluation/ml4srm/swan/db.properties
jaicore.experimentConfig = ./evaluation/ml4srm/swan/cwe79/experiments.cnf
