port = 8080

dataset.train = /scratch/hpc-prf-crnrw/weave/evaluation/ml4srm/swan/cwe89/cwe89.arff
dataset.test = /scratch/hpc-prf-crnrw/weave/evaluation/ml4srm/swan/cwe89/cwe89-owasp-benchmark.arff

# ------ML-Plan configuration

#duration in minutes
mlplan.timeout = 10
mlplan.timeout.node = 30
mlplan.timeout.candidate = 10
mlplan.seed = 76557
mlplan.cpu = 64

#-----Empirical evaluation
jaicore.databaseConfig = ./evaluation/ml4srm/swan/db.properties
jaicore.experimentConfig = ./evaluation/ml4srm/swan/cwe89/experiments.cnf

#-----Paths
paths.explainer = /scratch/hpc-prf-crnrw/weave/cli/src/main/java/de/fraunhofer/iem/weave/module/explainer/shap/shap_explainer.py
paths.output = /scratch/hpc-prf-crnrw/weave/evaluation/ml4srm/swan/cwe89/output
paths.python = python

shap.samples = 1000