port = 8080

dataset.train = ./evaluation/ml4srm/swan/cwe89/cwe89.arff
dataset.test = ./evaluation/ml4srm/swan/cwe89/cwe89-owasp-benchmark-methods.arff

# ------ML-Plan configuration

#duration in minutes
mlplan.timeout = 10
mlplan.timeout.node = 30
mlplan.timeout.candidate = 10
mlplan.seed = 76557
mlplan.cpu = 64

#-----Empirical evaluation
jaicore.databaseConfig = ./evaluation/ml4srm/swan/db.properties
jaicore.experimentConfig = ./evaluation/ml4srm/swan/cwe89/experiments.cnf

#-----Paths
paths.explainer = cli/src/main/java/de/fraunhofer/weave/cli/module/explainer/shap/shap_explainer.py
paths.output = cli/src/main/resources/out/weka/cwe89
paths.python = python3
