port = 8050

dataset.train = ./evaluation/ml4srm/swan/source/source.arff
dataset.test = ./evaluation/ml4srm/swan/source/source-owasp-benchmark-methods.arff

# ------ML-Plan configuration

#duration in minutes
mlplan.timeout = 60
mlplan.timeout.node = 30
mlplan.timeout.candidate = 10
mlplan.seed = 76557
mlplan.cpu = 64

#-----Empirical evaluation
jaicore.databaseConfig = ./evaluation/ml4srm/swan/db2.properties
jaicore.experimentConfig = ./evaluation/ml4srm/swan/source/experiments.cnf

#-----Paths
paths.explainer = cli/src/main/java/de/fraunhofer/weave/cli/module/explainer/shap/shap_explainer.py
paths.output = cli/src/main/resources/out/weka/source
paths.python = python3